### ISSUE TITLE
[Bug]: ERROR notifications are show as INFO

### ISSUE THREAD

**Issue by leoncruz** [akinsho/flutter-tools.nvim#209]
**Describe the bug**
When a error occours, notifications are shown as Info notifications insted of error. This happend with me when build a flutter projetc and with a project  already running and an error occours

**To Reproduce**

1. Create a new flutter project.
2. Create a proposital error on file.
3. Build the project
4. See notifications are INFO insted of ERROR panels

**Expected behavior**
The notification should appear as as error notifications

**Screenshots**
![error_as_info_notifications](https://user-images.githubusercontent.com/26262480/219918014-45f64749-fd68-4ab3-970a-de114351f292.png)

**System information**

- OS: Arch linux
- Flutter version: 3.7.
- Is flutter in $PATH: $HOME/.asdf/installs/flutter/3.7.3-stable/bin/flutter
- neovim version: 0.8.3

**Comment by akinsho** [comment]
Should be fixed by #210

**Comment by gcanoxl** [comment]
> Should be fixed by #210

This situation still happens to me, looking like this:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26963009/228221480-eebc60d6-c009-47c6-b2f3-e6f7de42595f.png">

**Comment by akinsho** [comment]
@gcanoxl from the images in your screenshot, those windows seem to be error windows so the notifications aren't being reported as info. Also this change has definitely been implemented. Are you sure your issue is the same as the OP's

**Comment by gcanoxl** [comment]
> @gcanoxl from the images in your screenshot, those windows seem to be error windows so the notifications aren't being reported as info. Also this change has definitely been implemented. Are you sure your issue is the same as the OP's

You said right, those notifications are being reported as the level of error. But what I wanted to say is that error-level notifications should not be reported using messages or nvim-notify, for popping so many notification windows at the same time definitely blocks users' sight from where codes are written.

Some plugins like `trouble.nvim` are better choices to do so.

**Comment by leoncruz** [comment]
@gcanoxl your problem is related to #197?
